### ISSUE TITLE
build magi-link-front end >>> { 'dist' folder does not found }

### ISSUE THREAD

**Issue by Abubaker779** [panoratech/Panora#731]
## ON Running Command 
> `` docker compose docker-compose.source.yml up ``
#####  build is failing hence image does not formed successfully.

![image](https://github.com/user-attachments/assets/114bc9d6-cbc9-437e-bba1-cbf137570b1d)

**Comment by Abubaker779** [comment]
@rflihxyz assign it to me i want to work on this issue.

**Comment by rflihxyz** [comment]
Hello, thanks for sharing about this issue.

I confirm I've been able to reproduce the issue using commit [bc4dbbe](https://github.com/panoratech/Panora/commit/bc4dbbe72730ce8a381c58bd5c46d01174d04459)
 
 The issue was reproduced on a Github codespace with 2core and 2GB RAM, but the build worked well on a more powerful machine. The build also works on mac (m3 pro).
 
 Something that fixes the build bug on low specs machines is creating a npmrc file at the root like this:
` echo -e "node-linker=hoisted\n package-import-method=clone-or-copy" > .npmrc`

Please confirm that fixes the bug for you @Abubaker779 :)

**Comment by rflihxyz** [comment]
Great! Closing the issue
